mqtt:
  sensor:
    - state_topic: "heatpumps/HOSTNAME/status"
      name: "NAME temperature"
      device_class: "temperature"
      value_template: '{{ value_json.roomTemperature | float }}'
      unit_of_measurement: "°C"

    - state_topic: "heatpumps/HOSTNAME/status"
      name: "NAME operating"
      value_template: '{{ value_json.operating | int }}'
      unit_of_measurement: "Operating"

    - state_topic: "heatpumps/HOSTNAME/settings"
      name: "NAME set temperature"
      device_class: "temperature"
      value_template: '{{ value_json.temperature }}'
      unit_of_measurement: "°C"

    - state_topic: "heatpumps/HOSTNAME/settings"
      name: "NAME power"
      value_template: '{{ value_json.power }}'

  switch:
    - name: "NAME power"
      command_topic: "heatpumps/HOSTNAME/control"
      state_topic: "heatpumps/HOSTNAME/settings"
      payload_on: '{"power":"ON"}'
      payload_off: '{"power":"OFF"}'
      state_on: "ON"
      state_off: "OFF"
      value_template: '{{ value_json.power }}'
      retain: false
      optimistic: false

  number:
    - name: "NAME set temperature"
      command_topic: "heatpumps/HOSTNAME/control"
      state_topic: "heatpumps/HOSTNAME/settings"
      min: 60
      max: 80
      mode: "box"
      optimistic: false
      step: 1
      unit_of_measurement: "°F"
      value_template: '{{ value_json.temperature * 9/5 + 32 }}'
      command_template: '{ "temperature": {{ (value-32)*5/9 }} }'
